language: php

php:
  - "7.0"
  - "7.1"

before_script:
  - composer install --no-scripts --no-interaction
  - composer dump-autoload -o

after_script:
    - bash <(curl -s https://codecov.io/bash)

script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml
